### ISSUE TITLE
expect 2 char weekday names

### ISSUE THREAD

**Issue by mtmail** [iandees/image-to-osm#1]
The tool extracted
```
name=Bike & Co
opening_hours=Mo-Fr 10:00-13:00; Mo-Fr 15:00-19:00; Wed 15:00-19:00; Sat 10:00-13:00
shop=bicycle
```

It understood German, the non-usual format, `name` and `shop` are correct.

https://openingh.openstreetmap.de/evaluation_tool/ complains that `Wed` and `Sat` should be `We` and `Sa` instead.

`Mo-Fr 15:00-19:00` also cancels out `Mo-Fr 10:00-13:00`. Should be `Mo-Fr 10:00-13:00, 15:00-19:00`.

I don't know if prompt engineering might work here. Or if giving the API the error messages from https://github.com/opening-hours/pyopening_hours as second step might work.

![photo](https://github.com/user-attachments/assets/8722b008-9849-41f4-90d7-ea0a61347278)

**Comment by iandees** [comment]
I think I got it to more reliably use the correct day name abbreviations in 756c7c7.

<img width="788" alt="image" src="https://github.com/user-attachments/assets/8599412c-7e06-40e9-88d5-6b8ab62c6dff">
