### ISSUE TITLE
Nothing tag-worthy found in the image

### ISSUE THREAD

**Issue by gy-mate** [iandees/image-to-osm#2]
Doesn't recognize a [recycling bin](https://www.openstreetmap.org/node/12138589502):
![IMG_4353](https://github.com/user-attachments/assets/ff334e4b-2192-4660-8429-27187080dbb1)

Or [bike stands](https://www.openstreetmap.org/node/726158415):
![IMG_4352](https://github.com/user-attachments/assets/3c81793b-e2ba-4b57-b121-25fc71d3f915)

I'm using Safari `17.6` on iOS `17.6.1`.

BTW this is an amazing idea, thanks! :)

**Comment by iandees** [comment]
Thanks for the report. I generalized the prompt a little more in 756c7c7 and it gives back reasonable tags for these images now.

**Comment by gy-mate** [comment]
Thank you, it works great! :)
